### ISSUE TITLE
Unable to edit an existing group

### ISSUE THREAD

**Issue by Robcwilliams** [RedHatInsights/insights-frontend#192]
I can filter using global groups & I can add a new one...but there doesn't seem to be a way anymore for me to modify an existing group. Limitation occurs in both Beta & Stable

**Comment by jharting** [comment]
This is now broken in beta due to https://github.com/RedHatInsights/insights-frontend/issues/191
It works in stable though.

These are the steps to modify a group:

* Adding more systems to a group:
    1. Open inventory
    2. Select systems you wish to add
    3. Click Actions --> Group Systems
    4. In the dropdown select an existing group


* Removing systems from a group
    1. Open inventory
    2. Use Global Filters to select your group
    3. Select systems you want removed
    4. Click Actions --> Remove systems from group <group_name>

![screenshot_20170727_173144](https://user-images.githubusercontent.com/167352/28678936-f5700240-72f1-11e7-9b84-2424fa5fe019.png)

**Comment by jharting** [comment]
fix deployed to `/insightsbeta`
